// Static data client. Reads pre-built JSON from /data (generated by
// scripts/build-data.mjs at build time). No backend required.

const DATA_BASE = `${import.meta.env.BASE_URL || '/'}data`.replace(/\/+$/, '');

async function getJson(path, { signal } = {}) {
  const res = await fetch(`${DATA_BASE}${path}`, { signal });
  if (!res.ok) throw new Error(`Data ${path}: ${res.status}`);
  return res.json();
}

export const api = {
  listBooks: (opts) => getJson('/books.json', opts),
  getBook: (bookId, opts) => getJson(`/books/${bookId}.json`, opts),
  getChapter: (bookId, chapterId, opts) => getJson(`/books/${bookId}/${chapterId}.json`, opts),
  getPeriod: (periodId, opts) => getJson(`/periods/${periodId}.json`, opts),
  geoUrl: (layer) => `${DATA_BASE}/geo/${layer}.geojson`,
};
